config/routes.rb
Stationary::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"
  

  resources :songs
  resources :seasons  do
      member do
             get 'generate'
      end
  end
  resources :playlists
  resources :stations
                       

end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Season < ActiveRecord::Base
   has_many :playlists, :dependent => :destroy
   
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  # GET /seasons
  # GET /seasons.xml
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seasons }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.xml
  def show
    @season = Season.find(params[:id])
    @stations = Station.order("name").all
    @playlists = Playlist.find_all_by_season_id(@season)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.xml
  def new
    @season = Season.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.xml
  def create
    @season = Season.new(params[:season])

    respond_to do |format|
      if @season.save
        format.html { redirect_to(@season, :notice => 'Season was successfully created.') }
        format.xml  { render :xml => @season, :status => :created, :location => @season }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @season.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seasons/1
  # PUT /seasons/1.xml
  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to(@season, :notice => 'Season was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @season.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.xml
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to(seasons_url) }
      format.xml  { head :ok }
    end
  end    
  
  
  # GET /seasons/1/generate
  def generate
     @season = Season.find(params[:id])
     @stations = Station.all
     @playlists = Playlist.find_all_by_season_id(@season)
     
     respond_to do |format|
       format.html { render :layout => false }
     end

     
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/generate.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>The Stationary Groove - TTC</title>
		  <%= stylesheet_link_tag 'widths', :id => "cssSize" %>
		  <%= stylesheet_link_tag 'map' %>
		  <%= javascript_include_tag "map" %> 
		  <%= csrf_meta_tag %>

</head>



<body>


<div id="holder">

<div class="mapdefault"><a name="mapstart"></a></div>

<h3 class="access">Yonge-University-Spadina Line</h3>

<dl class="map">
 
	<% @playlists.each do |playlist| %>
		<dt><a id="<%= playlist.station.codename %>"<% unless playlist.url.nil? %> href="<%= playlist.url %>"<% end %> class="location" target="_blank"><%= playlist.station.name %></a></dt>
		<dd class="yus"><h3>Stationary Groove - <%= playlist.station.name %> Station Playlist</h3>
	   <p class="downloadtext"><% unless playlist.url_text.nil? %><%= playlist.url_text %><% end %></p>
		<ul>
			<% Song.find_all_by_playlist_id(playlist).each do |song| %>
				<li><%= song.artist + " - " + song.title %></li>
			<% end %>
	   </ul>
	   <br />
			<% unless playlist.url.nil? %>
				<div class="downloadtext">Click the station dot to download this playlist</div>
			<% end %>
		</dd>


	<% end %>
	

</dl>



</div>



</body>
</html>

app/views/seasons/index.html.erb
<h1>Listing seasons</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><%= season.name %></td>
    <td><%= link_to 'Show', season %></td>
    <td><%= link_to 'Edit', edit_season_path(season) %></td>
    <td><%= link_to 'Destroy', season, :confirm => 'Are you sure?', :method => :delete %></td>
	 <td><%= link_to 'Generate', generate_season_path(season) %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @season.name %>
</p>

	<table>
		<% @stations.each do |station| %>
			<tr>
			<td><%= link_to station.name, playlist_path(Playlist.find_or_create_by_station_id_and_season_id(:station_id => station.id, :season_id => @season.id)) %></td>
			</tr>
	   <% end %>
   </table>

<p>&nbsp;</p>
<%= link_to 'Edit Season', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>