config/routes.rb
Stationary::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"
  

  resources :songs
  resources :seasons  do
      member do
             get 'generate'
      end
  end
  resources :playlists
  resources :stations
                       

end

app/models/station.rb
# == Schema Information
#
# Table name: stations
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  codename   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Station < ActiveRecord::Base
has_many :playlists, :dependent => :destroy  

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations
  # GET /stations.xml
  def index
    @stations = Station.all
    @newstation = Station.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.xml
  def show
    @station = Station.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.xml
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.xml
  def create
    @station = Station.new(params[:station])

    if @station.save
       redirect_to stations_path
    else
       flash[:error] = "Couldn't save station"
       redirect_to stations_path 
    end
  end

  # PUT /stations/1
  # PUT /stations/1.xml
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to(@station, :notice => 'Station was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @station.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.xml
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to(stations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :codename %><br />
    <%= f.text_field :codename %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Codename</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.name %></td>
    <td><%= station.codename %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
         
<p>&nbsp;</p>

<%= form_for @newstation do |f| %>
	<%= f.label :name, "Full station name"%>
	<%= f.text_field :name, :autofocus => true %><br />
	<%= f.label :codename, "HTML codename" %>
	<%= f.text_field :codename %>
	<%= f.submit %>
<% end %>


<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @station.name %>
</p>

<p>
  <b>Codename:</b>
  <%= @station.codename %>
</p>


<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>