config/routes.rb
Stationary::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"
  

  resources :songs
  resources :seasons  do
      member do
             get 'generate'
      end
  end
  resources :playlists
  resources :stations
                       

end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  artist      :string(255)
#  url         :string(255)
#  rank        :integer
#  playlist_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Song < ActiveRecord::Base
   belongs_to :playlist

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.xml
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.xml  { render :xml => @song }
    # end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.xml
  def create
    @song = Song.new(params[:song])
    if @song.save
       redirect_to playlist_path(@song.playlist)
    else
       flash[:error] = "Couldn't save song"
       redirect_to playlist(@song.playlist)
    end
  end
       

    # respond_to do |format|
    #   if @song.save
    #     format.html { redirect_to(@song, :notice => 'Song was successfully created.') }
    #     format.xml  { render :xml => @song, :status => :created, :location => @song }
    #   else
    #     format.html { render :action => "new" }
    #     format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
    #   end
    # end
    # end

  # PUT /songs/1
  # PUT /songs/1.xml
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to(@song, :notice => 'Song was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to(songs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :playlist_id %><br />
    <%= f.select :playlist_id, Playlist.find(:all).collect {|s| [s.station.name, s.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Url</th>
    <th>Rank</th>
    <th>Playlist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.title %></td>
    <td><%= song.artist %></td>
    <td><%= song.url %></td>
    <td><%= song.rank %></td>
    <td><%= song.playlist_id %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @song.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @song.artist %>
</p>

<p>
  <b>Url:</b>
  <%= @song.url %>
</p>

<p>
  <b>Rank:</b>
  <%= @song.rank %>
</p>

<p>
  <b>Playlist:</b>
  <%= @song.playlist_id %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>