config/routes.rb
Stationary::Application.routes.draw do
  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"
  

  resources :songs
  resources :seasons  do
      member do
             get 'generate'
      end
  end
  resources :playlists
  resources :stations
                       

end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id         :integer         not null, primary key
#  season_id  :integer
#  station_id :integer
#  url        :string(255)
#  url_text   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Playlist < ActiveRecord::Base
   belongs_to :season
   belongs_to :station
   has_many :songs, :dependent => :destroy
   
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  # GET /playlists
  # GET /playlists.xml
  def index
    @playlists = Playlist.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @playlists }
    end
  end

  # GET /playlists/1
  # GET /playlists/1.xml
  def show
    @playlist = Playlist.find(params[:id])
    @songs = Song.find_all_by_playlist_id(@playlist, :order => :rank)
    @song = Song.new
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.xml
  def new
    @playlist = Playlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
    @playlist = Playlist.find(params[:id])
  end

  # POST /playlists
  # POST /playlists.xml
  def create
    @playlist = Playlist.new(params[:playlist])

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to(@playlist, :notice => 'Playlist was successfully created.') }
        format.xml  { render :xml => @playlist, :status => :created, :location => @playlist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @playlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.xml
  def update
    @playlist = Playlist.find(params[:id])

    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to(@playlist, :notice => 'Playlist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @playlist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.xml
  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to(playlists_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :season_id %><br />
	 <%= f.select :season_id, Season.find(:all).collect {|s| [s.name, s.id] } %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br />
    <%= f.select :station_id, Station.find(:all).collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :url_text %><br />
    <%= f.text_field :url_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <tr>
    <th>Season</th>
    <th>Station</th>
    <th>Url</th>
    <th>Url text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.season.name %></td>
    <td><%= playlist.station.name %></td>
    <td><%= playlist.url %></td>
    <td><%= playlist.url_text %></td>
    <td><%= link_to 'Show', playlist %></td>
    <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
    <td><%= link_to 'Destroy', playlist, :method => :delete %></td>      <!-- :confirm => 'Are you sure?',  -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Season:</b>
  <%= @playlist.season.name %>
</p>

<p>
  <b>Station:</b>
  <%= @playlist.station.name %>
</p>

<p>
  <b>Url:</b> <%= link_to @playlist.url_text, @playlist.url %> 
</p>

<p><%= link_to 'Edit playlist info', edit_playlist_path(@playlist) %></p>

<p>
<table>
	<% unless @songs.empty? %>
		<% @songs.each do |song| %>
	 	<tr><td><% unless song.url.blank? %><a href="<%= song.url %>"><% end %>
				  <%= song.rank.to_s %>. <%= song.artist + " - " + song.title %>
				  <% unless song.url.blank? %></a><% end %> 
			    </td>
			    <td><%= link_to 'Edit song', edit_song_path(song) %> 
			        <%= link_to 'Delete', song, :confirm => 'Are you sure?', :method => :delete %>
		   </td></tr>
		<% end %>
	<% end %>
</table>

<p>&nbsp;</p>
<p><strong>Enter a new song:</strong></p>

<table>
	<tr>
		<td><%= form_for @song do |f| %>
			 <%= f.label :artist %>
			 <%= f.text_field :artist, :autofocus => true %>
			 <%= f.label :title, "Song title" %>
			 <%= f.text_field :title %>
			 <%= f.label :url, "URL" %>
			 <%= f.text_field :url %>
			 <%= f.hidden_field :playlist_id, :value => @playlist.id %>
			 <%= f.hidden_field :rank, :value => (@songs.count + 1) %>
			 <%= f.submit %> 
			 <% end %>
		</td>
</table>



<p>
<%= link_to 'Back', playlists_path %>
</p>